### ISSUE TITLE
New block types in MC 1.10+

### ISSUE THREAD

**Issue by LigH-de** [TOGoS/TMCMR#27]
In MC 1.10+, some new block types are not yet mapped. Some were reported in the debug output:

- 0x00CF (207) = beetroot (generated in villages in some beds)
- 0x00D0 (208) = grass_path (generated in villages on dirt with grass)
- 0x00D8 (216) = bone_block (generated usually underground to form fossils)

There are certainly more... I don't know how you calculate the average block color, so I can't provide results of the same algorithm.

**Comment by LigH-de** [comment]
I was not able to reproduce your averaging algorithm 100% exactly, but the remaining differences should be tiny. So, as good as it gets, I would suggest the following additions to **block-colors.txt**:

```
0x00CF:0x0	0x0901AB10	# Beetroot
0x00CF:0x1	0x0901AB10	# Beetroot
0x00CF:0x2	0x1701BB0F	# Beetroot
0x00CF:0x3	0x1701BB0F	# Beetroot
0x00CF:0x4	0x3600BE10	# Beetroot
0x00CF:0x5	0x3600BE10	# Beetroot
0x00CF:0x6	0x3600BE10	# Beetroot
0x00CF:0x7	0x65507135	# Beetroot
0x00D0	0xFF957C47	# Grass path
0x00D8	0xFFCDC9B1	# Bone block
```
Stage 0..6 of beetroot are identical to potatoes, only stage 7 is different (beige/purple).

Furthermore, you may like to fix "Unkonwn Sapling ID" to "Unknown Sapling ID".

**Comment by LigH-de** [comment]
Also enhanceable: Several sub-types of blocks (e.g. 0x0001 = Stone, but 0x0001:0x1 = Granite, 0x0001:0x2 = Smooth Granite, etc.).

**Comment by uncovery** [comment]
You can submit a pull request for the block-colors.txt with those in there

**Comment by LigH-de** [comment]
Yes, I already use this file via CLI option (with some additional tweaks possibly not desired here).

I was unsure whether I should offer my results as a whole replacement because I know that my values are not exact, and the original author will probably have a tool to calculate the "MIP 0" pixel value of block images. But I guess the absolute difference may be at most 2 for each RGBA component.

**Comment by uncovery** [comment]
I would just submit the changes. It's much easier to implement a pull request first and change the details later

**Comment by LigH-de** [comment]
I am not yet used to this workflow ... if I understood well, I would edit [block-data/block-colors.txt](https://github.com/TOGoS/TMCMR/blob/master/block-data/block-colors.txt) and then create a new pull request according to the sample to compare "yesterday" with "now" (`master@{1day}...master`)?

**Comment by uncovery** [comment]
Just click on the link that you pasted and then on the pen in the top right corner, save it and the create pull request.

**Comment by LigH-de** [comment]
TOGoS appears to be quite busy, still... as he already stated to never use it anymore, it seems to be more or less abandoned now.

**Comment by uncovery** [comment]
You might be right. You can always fork it and compile yourself

**Comment by LigH-de** [comment]
That would assume that I am a Java developer... but I am just a Java user, mainly. I don't see myself maintaining such a project.

**Comment by LigH-de** [comment]
Request got pulled - hoping for a new build after all recent patched got processed.
