### ISSUE TITLE
unmapped blocks in the current version

### ISSUE THREAD

**Issue by uncovery** [TOGoS/TMCMR#35]
Hi,
I was just updating to the latest Jar file (July 8th) and while mapping there are several blocks that are not in the current jar:

The following block IDs were not explicitly mapped to colors:
  0x00D0, 0x00E0, 0x00E1, 0x00E5, 0x00D5, 0x00E6, 0x00C7, 0x00D8, 0x00DB, 0x00DC

even if I use the https://github.com/TOGoS/TMCMR/blob/master/block-data/block-colors.txt, there are many blocks that are not accounted for:
The following block IDs were not explicitly mapped to colors:
  0x0082, 0x00C2, 0x00C6, 0x00C7, 0x00C8, 0x004D, 0x008F, 0x0090, 0x00DA, 0x009F,
  0x005F, 0x00A0, 0x00A1, 0x00A2, 0x0022, 0x00A5, 0x00E5, 0x0068, 0x00A8, 0x0069,
  0x00A9, 0x00AA, 0x00AB, 0x00AC, 0x00AF, 0x00B1, 0x00B8, 0x00B9, 0x00BC, 0x00BD,
  0x00BE

would it be possible to include those in the jar?

**Comment by TOGoS** [comment]
This was addressed by your pull request, right?  I just published a new jar labeled TMCMR-2017.09.02.jar.

**Comment by LigH-de** [comment]
On Sept. 1st ...

**Comment by uncovery** [comment]
Yes, that should fix it, thanks
